name = "risk-cancer"
compatibility_date = "2024-02-21"

[site]
bucket = "./dist"

[build]
command = "npm run build"
output_dir = "dist"

# 由于你的项目使用了 Vite 和 base path '/risk-cancer/'
[env.production]
routes = [
  { pattern = "/risk-cancer/*", dest = "/risk-cancer/index.html" }
]